backend:
  name: github
  repo: patrickfeeneydesign/gaze2025  # Replace with your actual GitHub username/repo name
  branch: main
  app_id: "Ov23liLtTJpkoaJPPuMx"   # The GitHub OAuth Client ID
 # Where this is the client_id from your GitHub OAuth App
  open_authoring: false
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "director"
    label: "Director's Page"
    files:
      - file: "content/director.json"
        label: "Director's Welcome"
        name: "directorJson"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Director Name", name: "directorName", widget: "string" }
          - { label: "Image Path", name: "image", widget: "string" }
          - { label: "Welcome Text", name: "welcomeText", widget: "text" }
